name: Deployment
on: 
  push:
    tags: 
     - patch
     - minor
     - major
jobs:
  deploy:
    runs-on: macos-11
    if: github.ref == 'chore/gh-actions'
    steps:
      - uses: actions/checkout@v1
      - name: Set env
        run: echo "RELEASE_TYPE=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Test
        run: |
          echo $RELEASE_TYPE
          echo ${{ env.RELEASE_TYPE }}
