name: Deployment
on: 
  push:
    branches:
      - master
      - 'chore/gh-actions'
    tags: 
     - patch
     - minor
     - major
jobs:
  depoly:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v1
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Test
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}
