name: Cocoapods
on: [pull_request]
jobs:
  LintInsights:
    runs-on: macos-11
    steps:
     - uses: actions/checkout@v2
     - name: Select Xcode version
       run: sudo xcode-select -s '/Applications/Xcode_13.2.app/Contents/Developer'
     - name: lint Insights
       run: pod lib lint --subspec="Insights" --allow-warnings
  LintCore:
    runs-on: macos-11
    steps:
     - uses: actions/checkout@v2
     - name: Select Xcode version
       run: sudo xcode-select -s '/Applications/Xcode_13.2.app/Contents/Developer'
     - name: lint Insights
       run: pod lib lint --subspec="Core" --allow-warnings
  LintUI:
    runs-on: macos-11
    steps:
     - uses: actions/checkout@v2
     - name: Select Xcode version
       run: sudo xcode-select -s '/Applications/Xcode_13.2.app/Contents/Developer'
     - name: lint Insights
       run: pod lib lint --subspec="UI" --allow-warnings
  LintSwiftUI:
    runs-on: macos-11
    steps:
     - uses: actions/checkout@v2
     - name: Select Xcode version
       run: sudo xcode-select -s '/Applications/Xcode_13.2.app/Contents/Developer'
     - name: lint Insights
       run: pod lib lint --subspec="SwiftUI" --allow-warnings